# Image
TAG := baseimage
USER := docker

BUILD_PARAMS := --build-arg DUID="${DUID}" --build-arg DGID="${DGID}" --build-arg USER="${USER}"

# Filepath
#PATH_DOCKER := $(PATH_ROOT)/src
#PATH_DOCKERFILE := $(PATH_DOCKER)/Dockerfile